name: CI

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Run Python tests
        run: |
          python3 --version
          python3 test.py

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Setup Gradle
        uses: gradle/gradle-build-action@v2
        with:
          gradle-version: '9.1'

      - name: Build Android library
        working-directory: android
        run: |
          gradle clean :dtc-database-android:assembleRelease --no-daemon --warning-mode all

      - name: Test Java Core
        working-directory: java
        run: |
          javac -cp "../data/lib/*" DTCDatabaseCore.java
          echo "Java compilation successful"
